### ISSUE TITLE
error

### ISSUE THREAD

**Issue by BBqlpt** [HeyMrRobot/Freqtrade-Adaptive-Renko-Strategy#2]
AttributeError: 'Series' object has no attribute 'append'
2023-07-28 14:44:15,739 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair MATIC/USDT:USDT: 'Series' object has no attribute 'append'
2023-07-28 14:44:15,744 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BTC/USDT:USDT
2023-07-28 14:44:15,745 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair ETH/USDT:USDT
2023-07-28 14:44:15,746 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair XRP/USDT:USDT
2023-07-28 14:44:15,748 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair SOL/USDT:USDT
2023-07-28 14:44:15,749 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair DOGE/USDT:USDT
2023-07-28 14:44:15,750 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair XLM/USDT:USDT
2023-07-28 14:44:15,751 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair IMX/USDT:USDT
2023-07-28 14:44:15,753 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair STMX/USDT:USDT
2023-07-28 14:44:15,754 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair LINK/USDT:USDT
2023-07-28 14:44:15,755 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair KNC/USDT:USDT
2023-07-28 14:44:15,756 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair LTC/USDT:USDT
2023-07-28 14:44:15,757 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair WLD/USDT:USDT
2023-07-28 14:44:15,758 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair 1000PEPE/USDT:USDT
2023-07-28 14:44:15,759 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair MKR/USDT:USDT
2023-07-28 14:44:15,761 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BCH/USDT:USDT
2023-07-28 14:44:15,762 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair OGN/USDT:USDT
2023-07-28 14:44:15,763 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair COMP/USDT:USDT
2023-07-28 14:44:15,764 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair ASTR/USDT:USDT
2023-07-28 14:44:15,765 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair OP/USDT:USDT
2023-07-28 14:44:15,766 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair MATIC/USDT:USDT
2023-07-28 14:44:20,533 - AdaptiveRenkoStrategy - INFO - Got the list of renko prices for pair BTC/USDT:USDT
2023-07-28 14:44:20,533 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'Series' object has no attribute 'append' calling <bound method IStrategy._analyze_ticker_internal of <AdaptiveRenkoStrategy.AdaptiveRenkoStrategy object at 0x7f7b2227d190>>
Traceback (most recent call last):
  File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 855, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 833, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1339, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/user_data/strategies/AdaptiveRenkoStrategy.py", line 97, in populate_indicators
    num_created_bars = renko_obj.do_next(dataframe.close.iloc[-1])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/user_data/strategies/pyrenko.py", line 75, in do_next
    self.source_prices.append(last_price)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)

**Comment by cearle4** [comment]
Same. 

The pandas class 'Series' has depreciated the .append method.

Pandas "version": "1.5.3"
